### ISSUE TITLE
当存在模块的情况，必须使用模块来取值？

### ISSUE THREAD

**Issue by africa1207** [cnyballk/wenaox#15]
版本:最新
比如这种情况 
// moduleA.js
`const state = {
	numA:1
}
const methods = {
	syncs: {
		addNumA(state,payload) {
			state.numA += payload
		}
	},
	asyncs: {}
}
export default {state,methods}`

// store.js
`
import {Store} from 'wenaox'
import moduleA from './module-a/index'

const state = {
	num:10
}
const methods = {
	syncs: {
		addNum(state,payload) {
			state.num += payload
		}
	},
	asyncs: {}
}

const store = new Store({state,methods, moduleA });

export default store
`

// index.js
`
import {ormComp} from 'wenaox'

const mapState = state =>({
  number: state.num,
  num: state.moduleA.numA
})
const mapMethods = methods => ({
  addNum: methods.addNum,
  addNumA: methods.moduleA.addNumA
})

Component(ormComp(mapState,mapMethods)({
  data:{},
  methods:{ 
    clickBtn() {
       this.addNum(12)
    },
    clickBtn2() {
      this.addNumA(5)
    }
  }
}));

`
这种情况就报错，‘Cannot read property 'numA' of undefined’，如果store.js中这样导出

const store = new Store({globle:{state,methods},moduleA }); 取值都按照模块来取值则正常

**Comment by cnyballk** [comment]
是的，没有兼容，如果需要兼容，你可以单独修改这个函数[点击查看](https://github.com/phonycode/wenaox/blob/master/dist/util.js#L18)
